theme: jekyll-theme-dinky
title: "Global ecosystem typology"

collections:
  Realms:
    output: true
  Biomes:
    output: true
  EFGs:
    output: true

defaults:
  - scope:
      path: ""
      type: "realms"
    values:
      layout: "realm"
  - scope:
      path: ""
      type: "Biomes"
    values:
      layout: "biome"
  - scope:
      path: ""
      type: "EFGs"
    values:
      layout: "EFG"
  - scope:
      path: ""
    values:
      layout: "default"
