theme: jekyll-theme-dinky
title: Global ecosystem typology
description: This site is dedicated to open consultation and review of profiles for Ecosystem Functional Groups (level 3) of the Global Ecosystem Typology.
collections:
  Realms:
    output: true
  Biomes:
    output: true
  EFGs:
    output: true

defaults:
  - scope:
      path: ""
      type: "realms"
    values:
      layout: "realm"
  - scope:
      path: ""
      type: "biomes"
    values:
      layout: "biome"
  - scope:
      path: ""
      type: "EFGs"
    values:
      layout: "EFG"
  - scope:
      path: ""
    values:
      layout: "default"
